pipeline{
    agent any
    stages{
        stage('cloning'){
            steps{
                git branch: 'feature/2025.06.22', credentialsId: 'github_credentials', url: 'https://github.com/ravi-dhanthala/Demoproject.git'
            }
        }
        stage('building'){
            steps{
                bat 'mvn clean install'
            }
        }
        stage('testing'){
            steps{
                bat 'mvn test'
            }
        }
        stage('Publishing artifacts'){
            steps{
                archiveArtifacts allowEmptyArchive: true, artifacts: 'target/*.jar', followSymlinks: false, onlyIfSuccessful: true
            }
        }
        stage('deploying'){
            steps{
                echo 'deplying code'
            }
        }
    }
    post {
    always {
        emailext(
            to: 'ravikumardhanthala6869@gmail.com',
            subject: "Build ${currentBuild.currentResult}: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
            body: """
                Build Status: ${currentBuild.currentResult}
                Job: ${env.JOB_NAME}
                Build Number: ${env.BUILD_NUMBER}
                URL: ${env.BUILD_URL}
            """
        )
    }
}

}